---
title: "ISLR_LAB_4"
author: "Ian Bates"
date: "4/11/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.6.1 The Stock Market Data

### 4.6.1 The Stock Market Data
```{r}
library(ISLR)
names(Smarket)

dim(Smarket )

summary(Smarket)

```

```{r}
cor(Smarket [,-9])

```


```{r}
attach(Smarket)
plot(Volume)

```


### 4.6.2 Logistic Regression

```{r}
glm.fits = glm(Direction ∼ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
               data = Smarket ,
               family = binomial)

 summary (glm.fits)

```
```{r}
coef(glm.fits)

glm.probs=predict(glm.fits,type="response")
glm.probs[1:10]
contrasts(Direction)
```

```{r}
glm.pred = rep("Down" , 1250)
glm.pred[glm.probs > .5] = " Up"
table(glm.pred ,Direction )

```




```{r}
train = (Year < 2005)
Smarket.2005 = Smarket[!train ,]
dim(Smarket.2005)
Direction.2005 = Direction[!train]

```



```{r}
glm.fits = glm(
  Direction∼Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
  data = Smarket ,
  family = binomial ,
  subset = train
)

glm.probs = predict(glm.fits, Smarket.2005, type = "response")

```


```{r}
glm.pred = rep("Down", 252)
glm.pred[glm.probs > .5] = " Up"
table(glm.pred , Direction.2005)

mean(glm.pred == Direction.2005)
mean(glm.pred != Direction.2005)


```

```{r}
glm.fits = glm(
  Direction∼Lag1 + Lag2 ,
  data = Smarket ,
  family = binomial ,
  subset = train
)
glm.probs = predict (glm.fits, Smarket.2005, type = "response")
glm.pred = rep("Down", 252)
glm.pred[glm.probs > .5] = "Up"
table(glm.pred , Direction.2005)
mean(glm.pred==Direction.2005)
106/(106+76)

```


```{r}
predict(glm.fits,
        newdata = data.frame(Lag1 = c(1.2 , 1.5),
                             Lag2 = c(1.1, -0.8)),
        type = "response")



```

### 4.6.3 Linear Discriminant Analysis

```{r}
library(MASS)
lda.fit = lda(Direction∼Lag1 + Lag2 , data = Smarket , subset = train)
lda.fit


```

```{r}
lda.pred=predict(lda.fit , Smarket.2005)
names(lda.pred)
```


```{r}
 lda.class=lda.pred$class

table(lda.class ,Direction.2005)

```



```{r}
sum(lda.pred$posterior[, 1] >= .5)
sum(lda.pred$posterior[, 1] < .5)
lda.pred$posterior[1:20, 1]
lda.class[1:20]
sum(lda.pred$posterior[, 1] > .9)

```

### 4.6.4 Quadratic Discriminant Analysis

```{r}
qda.fit = qda(Direction∼Lag1 + Lag2 , data = Smarket , subset = train)

qda.fit

```


```{r}
qda.class = predict (qda.fit , Smarket.2005)$class
table(qda.class , Direction.2005)
mean(qda.class==Direction.2005)

```

### 4.6.5 K-Nearest Neighbors

```{r}

library(class)
train.X = cbind(Lag1 , Lag2)[train , ]
test.X = cbind(Lag1 , Lag2)[!train , ]
train.Direction = Direction[train]


```

```{r}
set.seed(1)
knn.pred=knn(train.X,test.X,train.Direction ,k=1)
table(knn.pred ,Direction.2005)


```

```{r}
knn.pred=knn(train.X,test.X,train.Direction ,k=3)
table(knn.pred ,Direction.2005)
mean(knn.pred==Direction.2005)

```


### 4.6.6 An Application to Caravan Insurance Data

```{r}
dim(Caravan)
attach(Caravan)
summary(Purchase)

```

```{r}
standardized.X= scale(Caravan [,-86])
var(Caravan[ ,1])
var(Caravan[ ,2])
var(standardized.X[,1])
var(standardized.X[,2])


```

```{r}
test = 1:1000
train.X = standardized.X[-test , ]
test.X = standardized.X[test , ]
train.Y = Purchase[-test]
test.Y = Purchase[test]
set.seed(1)
knn.pred = knn(train.X, test.X, train.Y, k = 1)
mean(test.Y != knn.pred)

mean(test.Y!="No")

```


```{r}
table(knn.pred ,test.Y)
knn.pred=knn(train.X,test.X,train.Y,k=3)
table(knn.pred ,test.Y)
5/26
knn.pred=knn(train.X,test.X,train.Y,k=5)
table(knn.pred ,test.Y)
4/15

```


```{r}
glm.fits=glm(Purchase∼.,data=Caravan ,family=binomial ,subset=-test)
glm.probs=predict(glm.fits, Caravan [test ,], type="response")
glm.pred=rep("No",1000)
glm.pred[glm.probs >.5]="Yes"
table(glm.pred ,test.Y)
glm.pred=rep("No",1000)
glm.pred[glm.probs >.25]="Yes"
table(glm.pred ,test.Y)
11/(22+11)

```


